# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9b0a452f45aa552f2e0586c9f034e58259165b512f873d30cfa2fbe09a115fab953c1102ded572c64f67f75708e98fe344f75fec7a79ca64467a3bf295cab1c

test:
  secret_key_base: ffe330170860ae6eafdddf4f2f64e24f6fbb114a4936fe8b79aba9b08ddcf9205dd097e9504590030d95a74edb25f28453249e5ea95e9928e181a523a2f0fd9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
